CREATE SEQUENCE "PUBLIC"."MEMBER_SEQ" START WITH 1 INCREMENT BY 50;
CREATE CACHED TABLE "PUBLIC"."MEMBER"(
    "ID" BIGINT NOT NULL,
    "PHONE_NUMBER" CHARACTER VARYING(12) NOT NULL,
    "NAME" CHARACTER VARYING(25) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.MEMBER;
INSERT INTO "PUBLIC"."MEMBER" VALUES
(0, '2125551212', 'John Smith', 'john.smith@mailinator.com');
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."UK9QV6YHJQM8IAFTO8QK452GX8H" UNIQUE("EMAIL");